version: '3.3'

services:
  # MariaDB database service (MySQL compatible)
  db:
    container_name: astronomy-db
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: astronomy_db
      MARIADB_USER: astronomy
      MARIADB_PASSWORD: astronomy
    ports:
      - "3310:3306"
    volumes:
      - ./mc3jpyObs.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - astronomy-network

  # API service
  api:
    container_name: astronomy-api
    build: .
    restart: always
    depends_on:
      - db
    environment:
      FLASK_CONFIG: development
      FLASK_DEBUG: 1
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://astronomy:astronomy@astronomy-db:3306/astronomy_db
      SECRET_KEY: astronomy-api-secret-key
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
    command: >
      bash -c "
        echo '=== Astronomy API Startup ===' &&
        echo 'Current directory: '$(pwd) &&
        
        if [ ! -d '/app/templates' ]; then 
          echo 'Creating templates directory...';
          mkdir -p /app/templates/objects /app/templates/observations /app/templates/instruments /app/templates/places /app/templates/types /app/templates/properties;
        fi &&
        
        # Test database connection using SQLAlchemy 2.0 compatible code
        echo 'Testing database connection...' &&
        python test_db_sa2.py &&
        
        # Run the simple API server with database connection
        echo 'Starting simple API server...' &&
        python simple_api.py
      "
    networks:
      - astronomy-network
    
networks:
  astronomy-network:
    driver: bridge
