version: '3.3'

services:
  # MySQL database service
  db:
    container_name: astronomy-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: astronomy_db
      MYSQL_USER: astronomy
      MYSQL_PASSWORD: astronomy
    ports:
      - "3307:3306"
    volumes:
      - ./mc3jpyObs.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - astronomy-network

  # API service
  api:
    container_name: astronomy-api
    build: .
    restart: always
    depends_on:
      - db
    environment:
      FLASK_CONFIG: production
      DATABASE_URL: mysql+pymysql://astronomy:astronomy@astronomy-db:3306/astronomy_db
      SECRET_KEY: astronomy-api-secret-key
    ports:
      - "5000:5000"
    networks:
      - astronomy-network

networks:
  astronomy-network:
    driver: bridge
